import { WeekEffects } from "./week.effect";
import { Observable, of } from 'rxjs';
import { WeekService } from 'src/app/components/week/week.service';
import { TestBed } from '@angular/core/testing';
import { HttpClientModule } from '@angular/common/http';
import { provideMockActions } from '@ngrx/effects/testing';
import { hot, cold } from 'jasmine-marbles';
import * as WeekActions from '../actions/week.actions';

describe('*** Week Effects ***', () => {
  let effects: WeekEffects;
  let actions: Observable<any>;
  let weekService: WeekService;

  beforeAll( () => {
    TestBed.resetTestingModule();
    
    TestBed.configureTestingModule( {
      imports: [
        HttpClientModule,
      ],
      providers: [
        WeekEffects,
        provideMockActions( () => actions),
        WeekService
      ]
    });

    effects = TestBed.get(WeekEffects);
    weekService = TestBed.get(WeekService);
  });

    describe('** fetchWeekActivities$ **', () => {
      it('should return SetWeekActivities action', () => {
        const mockActivityResult = {
          week: '34',
          year: '2019',
          activities: []
        };
        spyOn(weekService, 'fetchActivities').and.returnValue(of(mockActivityResult));
        actions = hot('---a-', { a: new WeekActions.FetchWeekActivities({
          week: '34',
          year: '2019'
        }) });
        const expectedActivities = [
          { day: { day: 1, date: 1566169200000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566169200000,
              dayOfWeek: 1,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566169200000,
              dayOfWeek: 1,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566169200000,
              dayOfWeek: 1,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566169200000,
              dayOfWeek: 1,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566169200000,
              dayOfWeek: 1,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566169200000,
              dayOfWeek: 1,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
          { day: { day: 2, date: 1566255600000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566255600000,
              dayOfWeek: 2,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566255600000,
              dayOfWeek: 2,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566255600000,
              dayOfWeek: 2,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566255600000,
              dayOfWeek: 2,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566255600000,
              dayOfWeek: 2,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566255600000,
              dayOfWeek: 2,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
          { day: { day: 3, date: 1566342000000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566342000000,
              dayOfWeek: 3,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566342000000,
              dayOfWeek: 3,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566342000000,
              dayOfWeek: 3,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566342000000,
              dayOfWeek: 3,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566342000000,
              dayOfWeek: 3,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566342000000,
              dayOfWeek: 3,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
          { day: { day: 4, date: 1566428400000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566428400000,
              dayOfWeek: 4,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566428400000,
              dayOfWeek: 4,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566428400000,
              dayOfWeek: 4,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566428400000,
              dayOfWeek: 4,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566428400000,
              dayOfWeek: 4,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566428400000,
              dayOfWeek: 4,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
          { day: { day: 5, date: 1566514800000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566514800000,
              dayOfWeek: 5,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566514800000,
              dayOfWeek: 5,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566514800000,
              dayOfWeek: 5,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566514800000,
              dayOfWeek: 5,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566514800000,
              dayOfWeek: 5,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566514800000,
              dayOfWeek: 5,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
          { day: { day: 6, date: 1566601200000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566601200000,
              dayOfWeek: 6,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566601200000,
              dayOfWeek: 6,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566601200000,
              dayOfWeek: 6,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566601200000,
              dayOfWeek: 6,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566601200000,
              dayOfWeek: 6,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566601200000,
              dayOfWeek: 6,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
          { day: { day: 7, date: 1566687600000 }, activities: [
            {
              id: null,
              athleteUserId: null,
              categoryId: 'off',
              typeId: null,
              activityDay: 1566687600000,
              dayOfWeek: 7,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'swim',
              typeId: null,
              activityDay: 1566687600000,
              dayOfWeek: 7,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'bike',
              typeId: null,
              activityDay: 1566687600000,
              dayOfWeek: 7,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'run',
              typeId: null,
              activityDay: 1566687600000,
              dayOfWeek: 7,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'fitness',
              typeId: null,
              activityDay: 1566687600000,
              dayOfWeek: 7,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
            {
              id: null,
              athleteUserId: null,
              categoryId: 'race',
              typeId: null,
              activityDay: 1566687600000,
              dayOfWeek: 7,
              planned: 0,
              plannedContent: null,
              plannedDistance: null,
              plannedTime: null,
              realisedContent: null,
              realisedDistance: null,
              realisedTime: null,
              state: null
            },
          ] },
        ];
        const expected = cold('---b', { b: new WeekActions.SetWeekActivities(expectedActivities)});
        expect(effects.fetchWeekActivities$).toBeObservable(expected);
      });

      it('should return empty due to weekService error', () => {
        spyOn(weekService, 'fetchActivities').and.returnValue(cold('-#|', {}, 'error'));
        actions = hot('---a-', { a: new WeekActions.FetchWeekActivities({
          week: '34',
          year: '2019'
        }) });
        const expected = cold('----|');
        expect(effects.fetchWeekActivities$).toBeObservable(expected);
      });      
    });
});
